# Generated by Django 3.0.3 on 2020-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('dob', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('secret', models.CharField(default='Yet to Fil', max_length=10)),
                ('mk', models.BooleanField(default=False)),
                ('hs', models.BooleanField(default=False)),
                ('pv', models.BooleanField(default=False)),
                ('wc', models.BooleanField(default=False)),
                ('bt', models.CharField(default='Yet to Fil', max_length=10)),
                ('bp', models.CharField(default='Yet to Fil', max_length=10)),
                ('pulse', models.CharField(default='Yet to Fil', max_length=10)),
                ('cleaning', models.BooleanField(default=False)),
                ('facilities', models.BooleanField(default=False)),
            ],
        ),
    ]
