# Generated by Django 3.0.3 on 2020-05-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='secret',
        ),
    ]
