# Generated by Django 3.0.3 on 2020-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnproject', '0004_auto_20200524_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='h2h',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dob', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=10)),
                ('problem', models.TextField()),
            ],
        ),
    ]
