# Generated by Django 3.0.3 on 2020-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnproject', '0005_h2h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h2h',
            name='problem',
            field=models.TextField(null=True),
        ),
    ]
